# Generated by Django 4.0.4 on 2022-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
