# Generated by Django 4.0.4 on 2022-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_comment_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
