# Generated by Django 4.0.4 on 2022-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_comment_is_favorite_book_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(),
        ),
    ]
