# Generated by Django 4.0.4 on 2022-05-18 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_alter_favorite_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
