# Generated by Django 4.0.4 on 2022-05-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_book_is_favorite_book_is_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favorite',
            new_name='favorites',
        ),
    ]
