# Generated by Django 4.0.4 on 2022-05-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_is_favorite_book_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
    ]
