# Generated by Django 4.0.4 on 2022-05-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_book_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite',
        ),
    ]
