# Generated by Django 4.0.4 on 2022-05-21 10:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='favorite',
            field=models.BooleanField(default=1, verbose_name=accounts.models.CustomUser),
            preserve_default=False,
        ),
    ]
