# Generated by Django 4.0.4 on 2022-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_comment_likes_comment_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='favorite',
        ),
    ]
